### ISSUE TITLE
FOUC of the contrast switcher SVG icon

### ISSUE THREAD

**Issue by DirtyF** [smashingmagazine/redesign#274]
```gherkin
Given I open smashingmagazine.com in latest Firefox
When the page loads
Then I can see a FOUC of the contrast switcher SVG icon
```

Here is an animated GIF of the current behaviour:

![fouc-smashing](https://user-images.githubusercontent.com/103008/33139673-4539f3f8-cfae-11e7-9e3d-5db35df0175f.gif)

**Comment by vitalyfriedman** [comment]
Dear @DirtyF — the issue should be resolved now! Can you give it a try, please?

**Comment by DirtyF** [comment]
👋 @vitalyfriedman — If I reset the cache and reload the page the FOUC is still happening on Firefox 😕

**Comment by vitalyfriedman** [comment]
Dear @DirtyF — can you try one more time, please? Couldn't reproduce it in Firefox any longer! (Ah please with a cold cache).

**Comment by DirtyF** [comment]
Dear @vitalyfriedman, good news, the issue is not happening anymore. 🎉
